import 'dart:io';

/// Port of rikkahub's RootfsPatcher.
///
/// Patches an extracted rootfs so it can actually boot under proot/iSH:
/// writable resolv.conf, hosts entries, hostname, locale, tmp dirs.
class WorkspaceRootfsPatcher {
  const WorkspaceRootfsPatcher();

  void patch(
    Directory linuxDir, {
    WorkspaceRootfsPatchOptions options = const WorkspaceRootfsPatchOptions(),
  }) {
    final etcDir = Directory('${linuxDir.path}/etc');
    if (!etcDir.existsSync() ||
        etcDir.statSync().type != FileSystemEntityType.directory) {
      return;
    }

    _ensureRootfsDns(etcDir, options.nameservers);
    _ensureHosts(etcDir, options.hostname);
    _ensureHostname(etcDir, options.hostname);
    _ensureLocale(etcDir, options.locale);
    _ensureTempDirs(linuxDir);
  }

  void _ensureRootfsDns(Directory etcDir, List<String> nameservers) {
    final resolvConf = File('${etcDir.path}/resolv.conf');
    final isLink = Link(resolvConf.path).existsSync();
    var shouldWrite = false;
    if (isLink || !resolvConf.existsSync()) {
      shouldWrite = true;
    } else {
      final lines = resolvConf.readAsLinesSync();
      shouldWrite = !lines.any((line) {
        if (!line.trimLeft().startsWith('nameserver ')) return false;
        final server = line.trim().replaceFirst('nameserver', '').trim();
        return server.isNotEmpty && !localResolvers.contains(server);
      });
    }
    if (!shouldWrite) return;

    if (resolvConf.existsSync() || isLink) {
      try {
        resolvConf.deleteSync();
      } on FileSystemException {
        // ignore
      }
    }

    final servers = nameservers
        .where((s) => s.trim().isNotEmpty)
        .toSet()
        .take(maxDnsServers)
        .toList(growable: false);
    final effective =
        servers.isEmpty ? defaultDnsServers : servers;

    resolvConf.writeAsStringSync(
      '# Generated by Kelivo workspace.\n'
      '${effective.map((s) => 'nameserver $s').join('\n')}\n'
      'options edns0 trust-ad\n',
      flush: true,
    );
  }

  void _ensureHosts(Directory etcDir, String hostname) {
    final hosts = File('${etcDir.path}/hosts');
    final lines = hosts.existsSync()
        ? hosts.readAsLinesSync()
        : const <String>[];
    final hasIpv4 = lines.any(_hasLocalhost('127.0.0.1'));
    final hasIpv6 = lines.any(_hasLocalhost('::1'));
    if (hasIpv4 && hasIpv6) return;

    hosts.parent.createSync(recursive: true);
    final buf = StringBuffer();
    if (hosts.existsSync() &&
        hosts.lengthSync() > 0 &&
        !hosts.readAsStringSync().endsWith('\n')) {
      buf.writeln();
    }
    if (!hasIpv4) {
      buf.write('127.0.0.1 localhost');
      if (hostname.trim().isNotEmpty && hostname != 'localhost') {
        buf.write(' $hostname');
      }
      buf.writeln();
    }
    if (!hasIpv6) {
      buf.writeln('::1 localhost ip6-localhost ip6-loopback');
    }
    hosts.writeAsStringSync(buf.toString(),
        mode: FileMode.append, flush: true);
  }

  bool Function(String) _hasLocalhost(String address) {
    return (String line) {
      final normalized = line.split('#').first.trim().split(RegExp(r'\s+'));
      return normalized.first == address &&
          normalized.skip(1).contains('localhost');
    };
  }

  void _ensureHostname(Directory etcDir, String hostname) {
    final target = File('${etcDir.path}/hostname');
    if (target.existsSync() && target.readAsStringSync().trim().isNotEmpty) {
      return;
    }
    target.writeAsStringSync('${hostname.isEmpty ? 'localhost' : hostname}\n',
        flush: true);
  }

  void _ensureLocale(Directory etcDir, String locale) {
    final defaultDir = Directory('${etcDir.path}/default');
    defaultDir.createSync(recursive: true);
    final target = File('${defaultDir.path}/locale');
    final lines = target.existsSync()
        ? target.readAsLinesSync().toList()
        : <String>[];
    if (lines.any((l) => l.trim().startsWith('LANG='))) return;
    lines.add('LANG=$locale');
    target.writeAsStringSync('${lines.join('\n')}\n', flush: true);
  }

  void _ensureTempDirs(Directory linuxDir) {
    for (final path in ['tmp', 'var/tmp', 'root']) {
      Directory('${linuxDir.path}/$path').createSync(recursive: true);
    }
  }

  static const int maxDnsServers = 3;
  static const List<String> localResolvers = [
    '127.0.0.1',
    '127.0.0.53',
    '::1',
  ];
  static const List<String> defaultDnsServers = [
    '1.1.1.1',
    '8.8.8.8',
    '223.5.5.5',
  ];
}

class WorkspaceRootfsPatchOptions {
  const WorkspaceRootfsPatchOptions({
    this.nameservers = const [],
    this.hostname = 'localhost',
    this.locale = 'C.UTF-8',
  });

  final List<String> nameservers;
  final String hostname;
  final String locale;
}
